<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-5OUND92" name="Navegacion_Header1" tests="8" failures="2" timestamp="30 Aug 2017 21:15:46 GMT" time="88.593" errors="0">
  <testcase name="NuevosAlumnos" time="4.563" classname="Salle.TestClasses.prueba"/>
  <testcase name="NuevosAlumnos" time="3.667" classname="Salle.TestClasses.SalleHeader"/>
  <testcase name="Alumnos" time="4.148" classname="Salle.TestClasses.prueba"/>
  <testcase name="Alumni" time="2.574" classname="Salle.TestClasses.prueba"/>
  <testcase name="Alumnos" time="4.109" classname="Salle.TestClasses.SalleHeader"/>
  <testcase name="Alumni" time="2.305" classname="Salle.TestClasses.SalleHeader"/>
  <testcase name="Empresas" time="1.574" classname="Salle.TestClasses.SalleHeader">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at Salle.TestClasses.SalleHeader.Empresas(SalleHeader.java:96)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- Empresas -->
  <testcase name="Empresas" time="61.645" classname="Salle.TestClasses.prueba">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at Salle.TestClasses.prueba.Empresas(prueba.java:81)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- Empresas -->
</testsuite> <!-- Navegacion_Header1 -->
