<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SAPTEST_A00" name="Navegacion_Header2" tests="4" failures="1" timestamp="17 Aug 2017 15:14:04 GMT" time="20.36" errors="0">
  <testcase name="NuevosAlumnos" time="0.966" classname="Salle.TestClasses.prueba"/>
  <testcase name="Alumnos" time="2.24" classname="Salle.TestClasses.prueba"/>
  <testcase name="Alumni" time="6.298" classname="Salle.TestClasses.prueba"/>
  <testcase name="Empresas" time="0.563" classname="Salle.TestClasses.prueba">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at Salle.TestClasses.prueba.Empresas(prueba.java:81)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- Empresas -->
</testsuite> <!-- Navegacion_Header2 -->
