<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<<<<<<< HEAD
<testsuite hostname="DESKTOP-5OUND92" name="Navegacion_Header1" tests="9" failures="2" timestamp="8 Nov 2017 19:06:02 GMT" time="54.191" errors="0">
  <testcase name="NuevosAlumnos" time="10.029" classname="Salle.TestClasses.SalleHeader"/>
  <testcase name="NuevosAlumnos" time="10.031" classname="Salle.TestClasses.prueba"/>
  <testcase name="Alumnos" time="7.231" classname="Salle.TestClasses.SalleHeader"/>
  <testcase name="Alumnos" time="8.543" classname="Salle.TestClasses.prueba"/>
  <testcase name="Alumni" time="4.45" classname="Salle.TestClasses.SalleHeader"/>
  <testcase name="Alumni" time="4.554" classname="Salle.TestClasses.prueba"/>
  <testcase name="Empresas" time="2.24" classname="Salle.TestClasses.SalleHeader">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at Salle.TestClasses.SalleHeader.Empresas(SalleHeader.java:98)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- Empresas -->
  <testcase name="Empresas" time="1.729" classname="Salle.TestClasses.prueba">
=======
<testsuite hostname="SAPTEST_A00" name="Navegacion_Header1" tests="8" failures="2" timestamp="17 Aug 2017 15:18:55 GMT" time="19.174" errors="0">
  <testcase name="NuevosAlumnos" time="0.891" classname="Salle.TestClasses.prueba"/>
  <testcase name="NuevosAlumnos" time="0.684" classname="Salle.TestClasses.SalleHeader"/>
  <testcase name="Alumnos" time="1.572" classname="Salle.TestClasses.prueba"/>
  <testcase name="Alumnos" time="1.645" classname="Salle.TestClasses.SalleHeader"/>
  <testcase name="Alumni" time="1.256" classname="Salle.TestClasses.prueba"/>
  <testcase name="Empresas" time="1.627" classname="Salle.TestClasses.prueba">
>>>>>>> branch 'master' of https://github.com/ivan-molina/Salle.automation.git
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at Salle.TestClasses.prueba.Empresas(prueba.java:81)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- Empresas -->
<<<<<<< HEAD
  <testcase name="Universidades" time="1.423" classname="Salle.TestClasses.SalleHeader"/>
=======
  <testcase name="Alumni" time="4.412" classname="Salle.TestClasses.SalleHeader"/>
  <testcase name="Empresas" time="0.536" classname="Salle.TestClasses.SalleHeader">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at Salle.TestClasses.SalleHeader.Empresas(SalleHeader.java:96)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- Empresas -->
>>>>>>> branch 'master' of https://github.com/ivan-molina/Salle.automation.git
</testsuite> <!-- Navegacion_Header1 -->
