<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<<<<<<< HEAD
<testsuite hostname="DESKTOP-5OUND92" name="Salle.TestClasses.SalleHeader" tests="5" failures="0" timestamp="17 Nov 2017 12:17:28 GMT" time="13.177" errors="1">
  <testcase name="Alumni" time="2.354" classname="Salle.TestClasses.SalleHeader"/>
  <testcase name="Empresas" time="1.367" classname="Salle.TestClasses.SalleHeader">
=======
<testsuite hostname="SAPTEST_A00" name="Salle.TestClasses.SalleHeader" tests="4" failures="0" timestamp="25 Aug 2017 11:28:16 GMT" time="6.598" errors="1">
  <testcase name="Alumnos" time="1.417" classname="Salle.TestClasses.SalleHeader"/>
  <testcase name="NuevosAlumnos" time="1.369" classname="Salle.TestClasses.SalleHeader"/>
  <testcase name="Alumni" time="1.315" classname="Salle.TestClasses.SalleHeader"/>
  <testcase name="Empresas" time="2.497" classname="Salle.TestClasses.SalleHeader">
>>>>>>> branch 'master' of https://github.com/ivan-molina/Salle.automation.git
    <error type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:380)
<<<<<<< HEAD
	at Salle.TestClasses.SalleHeader.Empresas(SalleHeader.java:82)
=======
	at Salle.TestClasses.SalleHeader.Empresas(SalleHeader.java:101)
>>>>>>> branch 'master' of https://github.com/ivan-molina/Salle.automation.git
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
<<<<<<< HEAD
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
=======
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
>>>>>>> branch 'master' of https://github.com/ivan-molina/Salle.automation.git
]]>
    </error>
  </testcase> <!-- Empresas -->
<<<<<<< HEAD
  <testcase name="Universidades" time="1.150" classname="Salle.TestClasses.SalleHeader"/>
  <testcase name="Alumnos" time="3.328" classname="Salle.TestClasses.SalleHeader"/>
  <testcase name="NuevosAlumnos" time="4.978" classname="Salle.TestClasses.SalleHeader"/>
=======
>>>>>>> branch 'master' of https://github.com/ivan-molina/Salle.automation.git
</testsuite> <!-- Salle.TestClasses.SalleHeader -->
