<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<<<<<<< HEAD
<testsuite hostname="DESKTOP-5OUND92" name="Salle.TestClasses.prueba" tests="4" failures="0" timestamp="8 Nov 2017 19:06:02 GMT" time="25.643" errors="1">
  <testcase name="Alumni" time="4.557" classname="Salle.TestClasses.prueba"/>
  <testcase name="NuevosAlumnos" time="10.032" classname="Salle.TestClasses.prueba"/>
  <testcase name="Alumnos" time="9.325" classname="Salle.TestClasses.prueba"/>
  <testcase name="Empresas" time="1.729" classname="Salle.TestClasses.prueba">
=======
<testsuite hostname="SAPTEST_A00" name="Salle.TestClasses.prueba" tests="4" failures="0" timestamp="17 Aug 2017 15:18:55 GMT" time="5.794" errors="1">
  <testcase name="NuevosAlumnos" time="0.892" classname="Salle.TestClasses.prueba"/>
  <testcase name="Empresas" time="2.073" classname="Salle.TestClasses.prueba">
>>>>>>> branch 'master' of https://github.com/ivan-molina/Salle.automation.git
    <error type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:380)
	at Salle.TestClasses.prueba.Empresas(prueba.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- Empresas -->
<<<<<<< HEAD
=======
  <testcase name="Alumnos" time="1.572" classname="Salle.TestClasses.prueba"/>
  <testcase name="Alumni" time="1.257" classname="Salle.TestClasses.prueba"/>
>>>>>>> branch 'master' of https://github.com/ivan-molina/Salle.automation.git
</testsuite> <!-- Salle.TestClasses.prueba -->
